"""Reinstall model db in app_context()

Revision ID: 56f494844eee
Revises: 879dbea11988
Create Date: 2024-10-07 00:19:24.511197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f494844eee'
down_revision = '879dbea11988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_users')),
    sa.UniqueConstraint('email', name=op.f('uq_account_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_account_users_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_users')
    # ### end Alembic commands ###
