"""empty message

Revision ID: 56ff4a3825f0
Revises: d73e65794c6f
Create Date: 2024-10-09 00:54:49.967179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ff4a3825f0'
down_revision = 'd73e65794c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_attractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=False))
        batch_op.drop_column('distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_attractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
