"""empty message

Revision ID: 58ed86453226
Revises: d2fb72ad2bc4
Create Date: 2024-10-09 18:31:38.929981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ed86453226'
down_revision = 'd2fb72ad2bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dss_weights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attraction_type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_dss_weights_attraction_type_tourist_attraction_categories'), 'tourist_attraction_categories', ['attraction_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dss_weights', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dss_weights_attraction_type_tourist_attraction_categories'), type_='foreignkey')
        batch_op.drop_column('attraction_type')

    # ### end Alembic commands ###
