"""empty message

Revision ID: 618414b2f74a
Revises: a393fd842717
Create Date: 2024-10-10 01:13:08.303291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618414b2f74a'
down_revision = 'a393fd842717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dss_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('criteria', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], name=op.f('fk_dss_criteria_user_id_account_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dss_criteria'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dss_criteria')
    # ### end Alembic commands ###
