"""empty message

Revision ID: 7c01d07610d0
Revises: 56f494844eee
Create Date: 2024-10-08 00:55:13.217477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c01d07610d0'
down_revision = '56f494844eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_users', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
