"""empty message

Revision ID: a393fd842717
Revises: 58ed86453226
Create Date: 2024-10-09 23:38:48.610486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a393fd842717'
down_revision = '58ed86453226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dss_weights', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dss_weights_attraction_type_tourist_attraction_categories', type_='foreignkey')
        batch_op.drop_column('attraction_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dss_weights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attraction_type', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_dss_weights_attraction_type_tourist_attraction_categories', 'tourist_attraction_categories', ['attraction_type'], ['id'])

    # ### end Alembic commands ###
