"""Create model category attraction

Revision ID: d2fb72ad2bc4
Revises: 56ff4a3825f0
Create Date: 2024-10-09 01:11:26.439861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fb72ad2bc4'
down_revision = '56ff4a3825f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourist_attraction_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], name=op.f('fk_tourist_attraction_categories_user_id_account_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tourist_attraction_categories'))
    )
    with op.batch_alter_table('tourist_attractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tourist_attractions_category_id_tourist_attraction_categories'), 'tourist_attraction_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_attractions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tourist_attractions_category_id_tourist_attraction_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('tourist_attraction_categories')
    # ### end Alembic commands ###
