"""empty message

Revision ID: d73e65794c6f
Revises: 7c01d07610d0
Create Date: 2024-10-09 00:51:37.190684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73e65794c6f'
down_revision = '7c01d07610d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dss_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('facility', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], name=op.f('fk_dss_weights_user_id_account_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dss_weights'))
    )
    op.create_table('tourist_attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('facility', sa.Float(), nullable=False),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], name=op.f('fk_tourist_attractions_user_id_account_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tourist_attractions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourist_attractions')
    op.drop_table('dss_weights')
    # ### end Alembic commands ###
